import HomeArticles from 'components/HomeArticles'
import { type NextPage } from 'next'
import Head from 'next/head'
import Link from 'next/link'

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name='description' content='Generated by create-t3-app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main className='mx-auto max-w-[1000px] px-4 py-2'>
        <div className='mt-10 flex items-center justify-center gap-5'>
          <h1 className='text-5xl font-semibold'>Blog</h1>
          <Link
            className='rounded-md bg-slate-200 py-1.5 px-4 transition hover:bg-slate-800 text-sm hover:text-slate-100'
            href={'/admin'}
          >
            Go to Admin {'>'}
          </Link>
        </div>
        <HomeArticles />
      </main>
    </>
  )
}

export default Home
